<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MDA8086_Kit</AssemblyName>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mda8086Kit.Core\Mda8086Kit.Core.csproj" />
    <ProjectReference Include="..\Mda8086Kit.Io\Mda8086Kit.Io.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
